### ISSUE TITLE
outdated / wrong doc

### ISSUE THREAD

**Issue by SebSept** [webtrendi/clapp#2]
Hi, 
I'm trying your code.

The doc and code says that if argument that don't take values are not passed, ``getParam()`` returns `false` (https://github.com/webtrendi/clapp/blob/master/src/Clapp/CommandArgumentFilter.php#L76) but examples uses `!== null` : see readme : 
```php
// Retrieve parameter if set
if ($filter->getParam('h') !== null) {
    echo "Need help";
} 
```

bad start for someone trying ^^

**Comment by patforg** [comment]
Hi SebSept,

Thanks for pointing that out, the docs in the class describe the proper behaviour.

The example in the README will be corrected.

Thanks for pointing this out.  If you have any other feedback let me know.
